/**
 * @file app.config.ts
 * @description Per-game visual identity. Generated by tools/propagate-theme.js.
 * Edit the source script and re-run to update.
 */
export const APP_CONFIG = {
  name: "Belote",
  primary: "#3B82F6",
  secondary: "#1E40AF",
  splash: {
    glow: "rgba(30,64,175,0.6)",
    sallyGlow: "rgba(59,130,246,0.8)",
    pillBorder: "rgba(59,130,246,0.5)",
    pillBg: "rgba(30,64,175,0.15)",
    pillText: "#BFDBFE",
    suit: "♥",
    suit2: "♦",
  },
  slides: {
    slide2: { tint: ["rgba(59,130,246,0.55)","rgba(30,64,175,0.7)","rgba(8,15,40,0.95)"], variant: "grid" },
    slide3: { tint: ["rgba(99,102,241,0.45)","rgba(30,27,75,0.85)","rgba(8,15,40,0.95)"], variant: "fan" },
    slide4: { tint: ["rgba(245,158,11,0.45)","rgba(59,130,246,0.7)","rgba(8,15,40,0.95)"], variant: "spread" },
  },
} as const;

export type SlideVariant = 'fan' | 'scattered' | 'spread' | 'grid';
